config/routes.rb
Rails.application.routes.draw do

  root to: 'logins#show'
  
  resources :users, only: [:show] do 
    collection do
      get :show
    end
  end

  resource :books do 
    collection do 
      get :owned
      get :all
      get :borrowed
    end
  end

  resources :logins, only:[] do
    collection do 
      get :authenticate
      get :callback
      get :show
      get :logout
    end
  end
  

  resources :authors

  resources :checkouts,  only: [:new, :create, :show] do
  end 
  

end

app/models/book.rb
class Book < ActiveRecord::Base
    has_many :book_relationships
    has_many :users, :through => :book_relationships

    has_many :book_author_relationships
    has_many :authors, :through => :book_author_relationships

    ALLOWED_KEYS = %w(id title description publisher link image_url average_rating authors).freeze
    
    API_KEYS = %w(id average_rating).freeze
    BOOK_KEYS = %w(goodreads_book_id rating).freeze

    def self.all_goodread_book_ids
      all_book_ids =  Book.pluck(:goodreads_book_id)
    end

    def self.build_books(owned_books)
      
      unique_books!(owned_books)
      goodread_book_ids = owned_books.map{ |book| book['id'] }
      new_book_ids = goodread_book_ids - Book.all_goodread_book_ids
      new_book_details = owned_books.select { |book| book if new_book_ids.include?(book['id']) }

      books_arr = []
      new_book_details.each do |book|
        books_arr << book.select{ |key,_| ALLOWED_KEYS.include? key }  
      end
      books_arr.each do |book|
        BOOK_KEYS.zip(API_KEYS).each { |new_key, old_key| book[new_key] = book.delete(old_key) }
      end
      
      final_arr = []
      books_arr.each do |book_info|
        author = Author.new
        author.build_author(book_info["authors"]["author"])
        book = Book.new(book_info.except("authors"))
        
        book.authors << author
        final_arr << book
      end
      
      final_arr
    end

    def self.unique_books!(book_details)
      book_details.uniq! {|ele| ele["id"]}
    end



=begin
    def self.get_book(book_id)
      Book.where(id: book_id).first
    end

    def self.get_available_books
      raw_sql = "select *, book_count-subs_count as available from (
                  select total.id,total.title,total.image_url,total.book_count,COALESCE(subs.subs_count,0) subs_count
                  from		
                    (select book_id,count(s.book_id) subs_count from subscriptions s where s.is_active = 1 GROUP BY s.book_id) as subs
			                right join
			              (select b.id,b.title,b.image_url,count(br.book_id) book_count from book_relationships br inner join books b 
				              on b.id = br.book_id group by br.book_id) as total
			            on subs.book_id = total.id
              )a"
      ActiveRecord::Base.connection.select_all(raw_sql)
    end


    def self.create_unique_books( book_details, user )
      user_books = unique_books(book_details)
      if user_books
        user_books.each do |book|
          existing_book = Book.where(goodreads_book_id: book[:goodreads_book_id])

          if existing_book.blank?
            new_book = Book.new({
              goodreads_book_id: book[:goodreads_book_id] ,
              title: book[:title] ,
              description: book[:description] ,
              publisher: book[:publisher] ,
              link: book[:link] ,
              image_url: book[:image_url] ,
              rating: book[:average_rating]
            }) 

            author = Author.new({
              goodreads_author_id: book[:authors]["author"]["id"],
              name: book[:authors]["author"]["name"],
              image_url: book[:authors]["author"]["image_url"],
              link: book[:authors]["author"]["link"],
              rating: book[:authors]["author"]["average_rating"]
            })
            
            user.books << new_book
            new_book.authors << author
          else 
            user.books << existing_book   
          end
        end
      end
      user.save
    end

    private

    def self.unique_books(book_details)
      
      books_arr = book_details["GoodreadsResponse"]["owned_books"]["owned_book"]
      books_arr.uniq {|ele| ele["book"]["id"]}
      
      # books_arr = []
      # return if book_details["GoodreadsResponse"]["owned_books"]["owned_book"].nil? 
      # book_details["GoodreadsResponse"]["owned_books"]["owned_book"].each do |b|
      #   book = {
      #       goodreads_book_id: b["book"]["id"] ,
      #       title: b["book"]["title"] ,
      #       description: b["book"]["description"] ,
      #       publisher: b["book"]["publisher"] ,
      #       link: b["book"]["link"] ,
      #       image_url: b["book"]["image_url"] ,
      #       rating: b["book"]["average_rating"],
      #       authors: b["book"]["authors"]
      #   }
      #   books_arr << book 
      # end
      # books_arr.uniq {|ele| ele[:goodreads_book_id]}
  end
=end  

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def owned
    @user_books = 
      User.joins("inner join book_relationships br 
                    on users.id = br.user_id 
                  inner join books b 
                    on b.id = br.book_id 
                  inner join book_author_relationships bar 
                    on bar.book_id = b.id 
                  inner join authors a 
                    on a.id = bar.author_id ")
      .select("b.title,b.description,b.link,b.image_url,a.name,a.id author_id").where(id: session[:user_id])
  end

  def all
    @available_books =  Book.get_available_books                        
  end
  
  def borrowed

    user = User.where(id: session[:user_id]).first
    @user_p = UserPresenter.new(user,view_context)

    @books = User.select("B.*,S.*")
      .joins("INNER JOIN SUBSCRIPTIONS S 
              ON USERS.ID = S.USER_ID 
            INNER JOIN BOOKS B 
              ON B.ID = S.BOOK_ID")
      .where({id: session[:user_id]})
    
    #user = User.where({id: 10}).first
    #@books = user.subscriptions.includes(:book)  

  end

end

app/helpers/books_helper.rb
module BooksHelper
    def format_date dt
        dt.strftime('%F')
    end
    def show_status is_active
        is_active == 1 ? :Active : :Inactive
    end
    def get_color book_count
        book_count == 0 ? :red : :green
    end
end

app/views/books/partials/_all_books.html.erb
<div class="all_books">
    <% @available_books.each do |book| %>
        <div class="left book-container">
            <%= image_tag (book["image_url"]) %>
<!--
            <button class="button checkout <%= get_color(book['available']) %>"  data-bookid="<%=book['id']%>">
                <div class="title">Borrow</div>
                <div class="price"><%= book['available'] %>available</div>
            </button>
            -->
        <%= link_to 'Get this book', new_checkout_path(id: book['id']) %>
        </div>
        
    <% end %>
</div>

<script>
    $(document).ready(function(){
        $(".checkout").click(function(){
            var book_id = $(this).attr("data-bookid");
            location.href = '/checkouts/new?book_id='+ book_id;
        })
    })
</script>

app/views/books/partials/_book.html.erb
<script>
    function show_tooltip(ele,author_id){
        tooltip.ajax(ele, '/authors/'+author_id);
    }
</script>


<div class="col-sm-12" id="featured">   
    <div class="page-header text-muted">
        My Owned Books
    </div> 
</div>

<!--/top story-->
<% @user_books.each do |item|%>
    <div class="row">    
        
        <div class="col-sm-10" id="bookdetails">
            <h3><%= item.title %></h3>
            <h4><span class="label label-default " onmouseover="show_tooltip(this,<%= item.author_id %>)">
                <%= item.name %>
            </span></h4>
            <h4>
                <small class="text-muted">
                    <br>
                    <%= truncate item.description.html_safe, length: 300, :escape => false %>
                    <%= link_to 'read more', item.link %> 
                </small>
            </h4>
        </div>

        <div class="col-sm-2" id="bookimg">
            <%= link_to  item.link,  :class => "pull-right" do %>
                <%= image_tag (item["image_url"]) %>
            <% end %>
        </div> 
        <br>
    </div>
<% end %>    