config/routes.rb
Rails.application.routes.draw do

  root to: 'logins#show'
  
  resources :users, only: [:show] do 
    collection do
      get :show
    end
  end

  resource :books do 
    collection do 
      get :owned
      get :all
      get :borrowed
    end
  end

  resources :logins, only:[] do
    collection do 
      get :authenticate
      get :callback
      get :show
      get :logout
    end
  end
  

  resources :authors

  resources :checkouts,  only: [:new, :create, :show] do
  end 
  

end

app/views/layouts/partials/_sidebar.html.erb
<!-- sidebar -->
<div class="column col-sm-3" id="sidebar">
    
    <a class="logo" href="#">
        <%= image_tag @user_p.user.img_url, class: :profileimg %>
    </a>
    <%= link_to "Logout", logout_logins_path %>
    <ul class="nav">
        <li class="active"><a href="#featured">
            <%= @user_p.user.name %>
        </a>
        </li>
        <li><a href="#stories">
            <%= @user_p.user.address %>
        </a>
        </li>
        <li><a href="#stories">
            Member since <%= @user_p.get_timeframe %>
            <br> Join Date <%= @user_p.user.join_date %>
        </a>
        </li>
        <li>
            <%= link_to "My Owned Books", owned_books_path, remote: true %>
        </li>
        <li>
            <%= link_to "All Books", all_books_path, remote: true %>
        </li>
    </ul>
    <ul class="nav hidden-xs" id="sidebar-footer">
        <!--<li>-->
        <!--  <a href="http://www.bootply.com"><h3>Basis</h3>Made with <i class="glyphicon glyphicon-heart-empty"></i> by Bootply</a>-->
        <!--</li>-->
    </ul>
</div>
<!-- /sidebar -->